name: 'Create a new app'

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      sampleCode:
        description: Include Sample code (Y/N)
        required: false
        default: 'Y'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"

permissions:
  contents: write
  pull-requests: write
